=== diegosch21/IAW-proy3/conf/conf.dtd
<?xml version="1.0" encoding="UTF-8"?>
 <!ELEMENT conf (template, titulo, header, footer,anio, Homecontent, Contactocontent, BandasContent)>
 <!ELEMENT template (#PCDATA)>
 <!ELEMENT titulo (#PCDATA)>
 <!ELEMENT header (#PCDATA)>
 <!ELEMENT footer (#PCDATA)>
 <!ELEMENT anio (#PCDATA)>
  <!ELEMENT Homecontent (#PCDATA)>
 <!ELEMENT Contactocontent (#PCDATA)>
 <!ELEMENT BandasContent (#PCDATA)>

=== diegosch21/IAW-proy3/conf/conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE conf SYSTEM "conf.dtd">
<conf>
	<template>templates/template/template.html</template>
	<titulo>Pagina zarpada</titulo>
	<header>html/headers/header1.html</header>
	<footer>html/footers/footer1.html</footer>
	<Homecontent>html/contents/home.html</Homecontent>
	<Contactocontent>html/contents/contacto.html</Contactocontent>
	<Bandascontent>html/contents/bandas.html</Bandascontent>
</conf>
